define BORDER_THICKNESS 0.5

skinparam DefaultTextAlignment center
skinparam WrapWidth 120
skinparam Shadowing false
skinparam BackgroundColor White
skinparam RectangleBorderThickness BORDER_THICKNESS
skinparam ActivityBorderThickness BORDER_THICKNESS
skinparam ActivityArrowFontSize 11
skinparam AgentBorderThickness BORDER_THICKNESS
skinparam ArrowThickness BORDER_THICKNESS
skinparam ArrowFontStyle Plain
skinparam NoteBorderThickness BORDER_THICKNESS
skinparam ClassBorderThickness BORDER_THICKNESS