import React from 'react'
import Head from 'next/head'
import { GetStaticPaths, GetStaticProps, GetStaticPropsContext } from 'next'

import { blogPosts } from '../../lib/data'
import { BlogPost } from '../../interfaces'

import spacing from '../styles/spacing.module.css'
import classes from '../styles/single-post-template.module.css'


const BlogPage = ({ slug, title, date, content }: BlogPost) => {
    // TODO: Add some commenting system, disqus or someting like that.
    const disqusConfig = {
        shortname: process.env.GATSBY_DISQUS_NAME,
        config: {identifier: slug, title},
    }

    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name={title} content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>{title}</h1>
                <div>{content}</div>
            </main>
        </div>
    )
}

// TODO: Fix these ts-ignores
// @ts-ignore
export const getStaticProps: GetStaticProps = async (context: GetStaticPropsContext) => {
    console.log(context)
    const { params } = context
    return {
        // @ts-ignore
        props: blogPosts.find((post) => post.slug === params.slug),
    }
}

export const getStaticPaths: GetStaticPaths = async () => {
    return {
        paths: blogPosts.map((post) => ({
            params: {
                slug: post.slug,
            },
        })),
        fallback: false,
    }
}

export default BlogPage
