import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'

const About: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="about" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1> About </h1>
            </main>
        </div>
    )
}

export default About
