import type {NextPage} from 'next'
import {blogPosts} from '../lib/data'
import Link from 'next/link'
import React from 'react'
import Head from 'next/head'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1>My Blog</h1>
            </main>
            <div>
                {blogPosts.map((post) => (
                    <div key={post.slug}>
                        <div>
                            <Link href={`/blog/${post.slug}`}>
                                <a>{post.title}</a>
                            </Link>
                        </div>
                        <div>{post.date}</div>
                        <div>{post.content}</div>
                    </div>
                ))}
            </div>
        </div>
    )
}

export default Home
